local _, L = ...;
if GetLocale() == "deDE" then 
L["ADD_ITEM"] = "Gegenstand hinzufügen";
L["CHANGE_NAME"] = "Name ändern";
L["COMBINED"] = "Kombiniert";
L["COUNT_FORMAT_PERCENT"] = "Prozent";
L["COUNT_FORMAT_ABSOLUTE"] = "Absolut";
L["COUNT_FORMAT_NONE"] = "Keine";
L["CREATE_GROUP"] = "Gruppe erstellen";
L["DRAG_ITEM_OR_SET_ITEM_ID"] = "Legt einen Gegenstand in das Feld\noder tragt die Item ID ein.";
L["DEFINE_STOCK_GOALS"] = "Gebt die gewünschten Lagerstände an.";
L["FULLY_STOCKED"] = "Auf Lager";
L["GENERAL"] = "Allgemein";
L["GROUP"] = "Gruppe";
L["INCLUDE_ALL_CHARACTERS_FROM_THIS_REALM"] = "Alle Chraktere dieses Realms einbeziehen";
L["INCLUDE_CURRENT_CHARACTER"] = "Aktuellen Charakter einbeziehen";
L["ITEM_ALREADY_ON_LIST"] = "Dieser Gegenstand befindet sich bereits in der Liste.";
L["ITEM_ID"] = "Item ID";
L["ITEM_ID_INVALID"] = "Item ID ungültig";
L["ITEM"] = "Gegenstand";
L["ITEMS"] = "Gegenstände";
L["MINIMUM"] = "Minimum";
L["MAXIMUM"] = "Maximum";
L["NOT_FOUND"] = "Unbekannt";
L["PANEL"] = "Übersicht";
L["PROGRESS_FORMAT_FILL_TO_GOAL"] = "Bis Zwischenziel füllen";
L["PROGRESS_FORMAT_FILL_TO_MAXIMUM"] = "Bis Maximalziel füllen";
L["PROGRESS_TYPE"] = "Fortschrittsanzeige";
L["QUANTITY_TO_STOCK"] = "Bestandsziel";
L["REMOVE_FROM_LIST"] = "Von Liste entfernen";
L["REMOVE_GROUP"] = "Gruppe entfernen"
L["SETTINGS"] = "Einstellungen";
L["SHOW_TRACKER_OVERLAY"] = "Tracker Overlay anzeigen";
L["SHOW_IN_TRACKER"] = "Im Tracker Overlay anzeigen";
L["TOGGLE_TRACKER"] = "Tracker Overlay ein- oder ausblenden";
L["TOGGLE_PANEL"] = "Panel ein- oder ausblenden";
L["STOCK_COUNT_FORMAT"] = "Bestandsformat";
L["STOCK_LEVEL"] = "Bestand";
L["TRACKER"] = "Tracker Overlay";
L["UNCATEGORIZED"] = "Ohne Gruppe";
L["UNTRACK"] = "Nicht mehr im Tracker anzeigen"
end