local _, L = ...;
if GetLocale() == "deDE" then
L.T["ADD_ITEM"] = "Gegenstand hinzufügen";
L.T["CHANGE_NAME"] = "Name ändern";
L.T["COMBINED"] = "Kombiniert";
L.T["COUNT_FORMAT_PERCENT"] = "Prozent";
L.T["COUNT_FORMAT_ABSOLUTE"] = "Absolut";
L.T["COUNT_FORMAT_NONE"] = "Keine";
L.T["CREATE_GROUP"] = "Neue Gruppe erstellen";
L.T["CURRENCY"] = "Abzeichen";
L.T["DRAG_ITEM_OR_SET_ITEM_ID"] = "Legt einen Gegenstand in das Feld\noder tragt die Item ID ein.";
L.T["DEFINE_STOCK_GOALS"] = "Gebt die gewünschten Lagerstände an.";
L.T["FULLY_STOCKED"] = "Auf Lager";
L.T["GATHERING_OBJECTIVE_COMPLETE"] = "Sammelziel erreicht.";
L.T["GENERAL"] = "Allgemein";
L.T["GROUP"] = "Gruppe";
L.T["INCLUDE_ALL_CHARACTERS_FROM_THIS_REALM"] = "Alle Chraktere dieses Realms einbeziehen";
L.T["INCLUDE_CURRENT_CHARACTER"] = "Aktuellen Charakter einbeziehen";
L.T["ITEM_ALREADY_ON_LIST"] = "Dieser Gegenstand befindet sich bereits in der Liste.";
L.T["ITEM_ID"] = "Item ID";
L.T["ITEM_ID_INVALID"] = "Item ID ungültig";
L.T["ITEM"] = "Gegenstand";
L.T["ITEMS"] = "Gegenstände";
L.T["MINIMUM"] = "Minimum";
L.T["MAXIMUM"] = "Maximum";
L.T["NOT_FOUND"] = "Unbekannt";
L.T["PANEL"] = "Übersicht";
L.T["PLAY_SOUNDS"] = "Soundeffekte abspielen";
L.T["PROGRESS_FORMAT_FILL_TO_GOAL"] = "Bis Zwischenziel füllen";
L.T["PROGRESS_FORMAT_FILL_TO_MAXIMUM"] = "Bis Maximalziel füllen";
L.T["PROGRESS_TYPE"] = "Fortschrittsanzeige";
L.T["QUANTITY_TO_STOCK"] = "Bestandsziel";
L.T["REMOVE_FROM_LIST"] = "Von Liste entfernen";
L.T["REMOVE_GROUP"] = "Gruppe entfernen"
L.T["SETTINGS"] = "Einstellungen";
L.T["SHOW_TRACKER_OVERLAY"] = "Tracker Overlay anzeigen";
L.T["SHOW_IN_TRACKER"] = "Im Tracker Overlay anzeigen";
L.T["SHOW_OBJECTIVE_NOTIFICATION"] = "Fortschrittbenachrichtigung im Questverfolgungsstil";
L.T["STOCK_COUNT_FORMAT"] = "Bestandsformat";
L.T["STOCK_LEVEL"] = "Bestand";
L.T["TOGGLE_TRACKER"] = "Tracker Overlay ein- oder ausschalten";
L.T["TOGGLE_PANEL"] = "Gather Panel ein- oder ausblenden";
L.T["TRACKER"] = "Tracker Overlay";
L.T["UNCATEGORIZED"] = "Ohne Gruppe";
L.T["UNTRACK"] = "Nicht mehr im Tracker anzeigen"
end
