GATHERPANEL_COUNT_FORMAT_PERCENT = "Prozent";
GATHERPANEL_COUNT_FORMAT_ABSOLUTE = "Absolut";
GATHERPANEL_COUNT_FORMAT_NONE = "Keine";
GATHERPANEL_PROGRESS_FORMAT_FILL_TO_GOAL = "Bis Zwischenziel füllen";
GATHERPANEL_PROGRESS_FORMAT_FILL_TO_MAXIMUM = "Bis Maximalziel füllen";